<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Posts extends Model
{
    //
    public function getRouteKeyName()
    {
        return 'id'; // TODO: Change the autogenerated stub
    }
}
